name: Docs
on:
  push:
    branches:
      - '*'
      - '!docs'
    paths:
      - "src/**"
      - "docs/**"
      - "static/**"
      - "scripts/docs.ts"
      - "package.json"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Install Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build documentation
        run: pnpm run docs

      - name: Deploy documentation
        uses: dbots-pkg/action-docs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update docs in repo
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/*.md
          message: 'chore(docs): auto-update docs'
