name: Tests
on:
  push:
    branches:
      - "*"
      - "!docs"
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
      - ".github/workflows/test.yml"
  pull_request_target:
    branches:
      - "*"
      - "!docs"
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Install Node v16
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm run test
